name: Docker Build and Push

on:
  push:
    branches: [main]
    paths:
      - "build.Dockefile"
      - "Makefile"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push
        run: |
          docker run --rm --privileged linuxkit/binfmt:v0.8
          make
